; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:genericSTM32F401CC]
platform = ststm32
board = genericSTM32F401CC
framework = cmsis
upload_protocol = stlink
debug_tool = stlink
build_type = debug
build_flags = 
	-I include/COTS_H
	-I include/COTS_H/HAL
	-I include/COTS_H/MCAL
	-I include/COTS_H/OS
check_tool = cppcheck
check_flags = cpp_check --enable=all



; // to push to both remote repos:
		; git push origin aboelyazeedDev
		; git push kishkrepo aboelyazeedDev:Ahmed_Aboelyazeed

; ONLY when Git tells you:
	; non-fast-forward
; Then you do (for origin only):
		; git pull origin aboelyazeedDev --rebase
		; git push origin aboelyazeedDev

